# Generated by Django 5.2.4 on 2025-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
