# Generated by Django 5.2.4 on 2025-08-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_tasks_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='added_by',
        ),
    ]
